name: Rust Continuous-Integration

on: [push, pull_request]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add component
        run: |
          rustup set profile minimal
          rustup install nightly
          rustup target add riscv64gc-unknown-none-elf
          rustup override set nightly
          rustup component add rustfmt
      - name: Cargo fmt
        run: cargo fmt --all --check

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add component
        run: |
          rustup set profile minimal
          rustup install nightly
          rustup target add riscv64gc-unknown-none-elf
          rustup override set nightly
      - name: Cargo check
        run: cargo check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add component
        run: |
          rustup set profile minimal
          rustup install nightly
          rustup target add riscv64gc-unknown-none-elf
          rustup override set nightly
          rustup component add rustfmt
      - name: Cargo clippy
        run: cargo clippy -- -D warnings
